feat(front): update front using vuejs and material style
looztra/guestbook-api-server pull request #4
Opened 2017-10-21 14:54 UTC by T3kstiil3

Le but de cette PR est de migrer le front AngularJs en Vuejs avec une petite touche de material design (vuetifyjs)

2017-10-21 15:12 UTC, NathanDM requested changes
🦄

2017-10-21 15:12 UTC, NathanDM commented on guestbook-simple-frontend/src/main/html/index.html
> +              <br>
prefer use

```css
class="mb-4"
```

2017-10-21 15:12 UTC, NathanDM commented on guestbook-simple-frontend/src/main/html/index.html
> +                <template v-for="message in messages">
missing :key

2017-10-21 15:12 UTC, NathanDM commented on guestbook-simple-frontend/src/main/html/index.html
> +                  <v-list-tile avatar @click="">
remove unused @click

2017-10-21 15:12 UTC, NathanDM commented on guestbook-simple-frontend/src/main/html/index.html
> +                      <img src="https://www.welcometothejungle.co/uploads/company/logo/zenika.png">
missing alt="Zenika logo"

2017-10-21 15:12 UTC, NathanDM commented on guestbook-simple-frontend/src/main/html/index.html
> +                      <v-list-tile-sub-title>Server: {{message.metadata.apiServerName}}</v-list-tile-sub-title>
missing space after inside bracket {{ }}

2017-10-21 15:12 UTC, NathanDM commented on guestbook-simple-frontend/src/main/html/index.html
> +              <v-toolbar color="red darken-4" dark light dense v-if="messages.length">
what append when "dark" & "light"  are both present ?

2017-10-21 15:12 UTC, NathanDM commented on guestbook-simple-frontend/src/main/html/index.html
> +              if(response.ok) return response.json()
i'm not a big fan of linear conditional

2017-10-21 15:12 UTC, NathanDM commented on guestbook-simple-frontend/src/main/html/index.html
> +              console.log("[/guestbook/messages] status code: " + status)
remove console.log ?

2017-10-21 15:12 UTC, NathanDM commented on guestbook-simple-frontend/src/main/html/index.html
> +            console.log("[/guestbook/messages] status code: " + status)
console.log ?
prefer console.warn / error

2017-10-21 15:12 UTC, NathanDM commented on guestbook-simple-frontend/src/main/html/index.html
>  </html>
new line a end of files :) @tiste

2017-10-21 15:15 UTC, Gillespie59 commented on guestbook-simple-frontend/src/main/confd/templates/app.config.js.tmpl
> +var apiServerRootUrl = '{{getv "/guestbook/frontend/api/server/root/url"}}';
un petit const ou let ?

2017-10-21 15:15 UTC, Gillespie59 commented on guestbook-simple-frontend/src/main/html/config/app.config.js
> +var apiServerRootUrl = 'http://localhost:8080';
idem const

2017-10-21 15:15 UTC, Gillespie59 commented on guestbook-simple-frontend/src/main/html/index.html
> +              <br>
C'est moche les br. Tu peux avoir un margin ?

2017-10-21 15:15 UTC, Gillespie59 commented on guestbook-simple-frontend/src/main/html/index.html
> +                <v-toolbar-title style="font-size: 15px;">Message<template v-if="messages.length > 1">s ({{messages.length}})</template></v-toolbar-title>
style dans une classe CSS

2017-10-21 15:15 UTC, Gillespie59 commented on guestbook-simple-frontend/src/main/html/index.html
> +                  <v-list-tile avatar @click="">
click vide

2017-10-21 15:15 UTC, Gillespie59 commented on guestbook-simple-frontend/src/main/html/index.html
> +  <title>GuestBook</title>
rajoute la balise meta <meta charset="utf-8">

2017-10-21 15:15 UTC, Gillespie59 commented on guestbook-simple-frontend/src/main/html/index.html
> +            console.log("[/guestbook/messages] status code: " + status)
console.log ?

2017-10-21 15:15 UTC, Gillespie59 commented on guestbook-simple-frontend/src/main/html/index.html
> +            console.log("[/guestbook/messages] status code: " + status)
double ou simple quote ?

2017-10-21 15:15 UTC, Gillespie59 commented on guestbook-simple-frontend/src/main/html/index.html
> +              userName: user,
tu ne peux pas nommer tes paramètres de méthode userName et content ? Pour pouvoir utiliser la syntaxe : 

```
{
  userName,
  content
}
```

2017-10-21 15:16 UTC, Gillespie59 commented on guestbook-simple-frontend/src/main/html/index.html
> +<html>
ajoute l'attribut lang

2017-10-21 15:21 UTC, Gillespie59 commented on guestbook-simple-frontend/src/main/html/index.html
> +          fetch(`${apiServerRootUrl}/api/v1/version`)
le /api/v1 ne peut pas être externalisé ?

2017-10-21 15:21 UTC, Gillespie59 commented on guestbook-simple-frontend/src/main/html/index.html
> +          return datetime
un return direct? les deux lignes suivantes servent à quoi ?

2017-10-21 15:21 UTC, T3kstiil3 commented on guestbook-simple-frontend/src/main/html/index.html
> +              <v-toolbar color="red darken-4" dark light dense v-if="messages.length">
grey 👯

2017-10-21 15:29 UTC, T3kstiil3 commented on guestbook-simple-frontend/src/main/html/index.html
> +                  <v-list-tile avatar @click="">
c'est pour avoir l'effet au survol c'est dans la doc vuetify :/

2017-10-21 15:43 UTC, T3kstiil3 commented on guestbook-simple-frontend/src/main/html/index.html
> +                  <v-list-tile avatar @click="">
pour avoir cet effet : 
![image](https://user-images.githubusercontent.com/3717296/31853354-4c6b397e-b687-11e7-8edf-a0f8f9206735.png)

2017-10-21 15:43 UTC, T3kstiil3 commented on guestbook-simple-frontend/src/main/html/index.html
> +            console.log("[/guestbook/messages] status code: " + status)
il y en avait avant dans le code de @looztra du coup je les ai laissé :/

2017-10-22 08:52 UTC, looztra commented
merci!

2017-10-22 08:52 UTC, merged